/**
 * 构建脚本：将 src/ 模块打包 + frontend/ 文件内联 → dist/worker.js
 * 用法: node build.js
 */
const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

// 读取前端文件
const pkg = require('./package.json');
let htmlContent = fs.readFileSync(path.join(__dirname, 'frontend/index.html'), 'utf-8');
htmlContent = htmlContent.replace(/\{\{VERSION\}\}/g, pkg.version);
const cssContent = fs.readFileSync(path.join(__dirname, 'frontend/css/style.css'), 'utf-8');
const jsFiles = [
    'dom.js', 'state.js', 'accounts.js', 'deploy.js', 'vars.js',
    'history.js', 'yxip.js', 'workbench.js', 'starfield.js'
];
const jsContent = jsFiles
    .map(f => fs.readFileSync(path.join(__dirname, 'frontend/js', f), 'utf-8'))
    .join('\n\n');

// 下载 SweetAlert2 以便内联（消除 CDN 依赖，离线可用）
let sweetalert2Content = '';

(async () => {
try {
    console.log('📥 Downloading SweetAlert2...');
    const https = require('https');
    const download = new Promise((resolve, reject) => {
        https.get('https://cdn.jsdelivr.net/npm/sweetalert2@11', (res) => {
            if (res.statusCode !== 200) { reject(new Error('HTTP ' + res.statusCode)); return; }
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => resolve(data));
        }).on('error', reject);
    });
    sweetalert2Content = await Promise.race([
        download,
        new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), 10000))
    ]);
    console.log('✅ SweetAlert2 downloaded (' + (sweetalert2Content.length / 1024).toFixed(1) + ' KB)');
} catch (e) {
    console.warn('⚠️  SweetAlert2 download failed, falling back to CDN: ' + e.message);
    sweetalert2Content = '';
}

// 注入前端资源到全局变量（供 src/index.ts 使用）
const frontendBundle = `
// AUTO-GENERATED by build.js — DO NOT EDIT
export const FRONTEND_VERSION = ${JSON.stringify('V' + pkg.version)};
export const FRONTEND_HTML = ${JSON.stringify(htmlContent)};
export const FRONTEND_CSS = ${JSON.stringify(cssContent)};
export const FRONTEND_JS = ${JSON.stringify(jsContent)};
export const FRONTEND_SWEETALERT2 = ${JSON.stringify(sweetalert2Content)};
`;

fs.writeFileSync(path.join(__dirname, 'src/frontend-bundle.ts'), frontendBundle, 'utf-8');

// 删除旧输出文件 (避免占用锁定)
try { fs.unlinkSync(path.join(__dirname, 'dist/worker.js')); } catch(e) { /* 文件不存在则跳过 */ }

// esbuild 打包 (absroot 保证不受 cwd 影响)
const absroot = __dirname;
esbuild.buildSync({
    absWorkingDir: absroot,
    entryPoints: [path.join(absroot, 'src/index.ts')],
    bundle: true,
    outfile: path.join(absroot, 'dist/worker.js'),
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    minify: true,
    banner: {
        js: `// Worker 智能中控 — 前后端分离构建 (${new Date().toISOString()})`
    }
});


// 自动更新 compatibility_date 为今天（优先 wrangler.local.toml）
try {
    const localToml = path.join(__dirname, 'wrangler.local.toml');
    const tomlPath = fs.existsSync(localToml) ? localToml : path.join(__dirname, 'wrangler.toml');
    const today = new Date().toISOString().split('T')[0];
    let toml = fs.readFileSync(tomlPath, 'utf-8');
    toml = toml.replace(/compatibility_date = "\d{4}-\d{2}-\d{2}"/, 'compatibility_date = "' + today + '"');
    fs.writeFileSync(tomlPath, toml, 'utf-8');
    console.log('📅 compatibility_date → ' + today + ' (' + path.basename(tomlPath) + ')');
} catch (e) { /* toml 不存在则跳过 */ }
console.log('✅ Build complete → dist/worker.js');
})();
