/**
 * 构建脚本：将 src/ 模块打包 + frontend/ 文件内联 → dist/worker.js
 * 用法: node build.js
 */
const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

// 读取前端文件
const htmlContent = fs.readFileSync(path.join(__dirname, 'frontend/index.html'), 'utf-8');
const cssContent = fs.readFileSync(path.join(__dirname, 'frontend/css/style.css'), 'utf-8');
const jsFiles = [
    'state.js', 'accounts.js', 'deploy.js', 'vars.js',
    'history.js', 'yxip.js', 'workbench.js', 'starfield.js'
];
const jsContent = jsFiles
    .map(f => fs.readFileSync(path.join(__dirname, 'frontend/js', f), 'utf-8'))
    .join('\n\n');

// 注入前端资源到全局变量（供 src/index.ts 使用）
const frontendBundle = `
// AUTO-GENERATED by build.js — DO NOT EDIT
export const FRONTEND_HTML = ${JSON.stringify(htmlContent)};
export const FRONTEND_CSS = ${JSON.stringify(cssContent)};
export const FRONTEND_JS = ${JSON.stringify(jsContent)};
`;

fs.writeFileSync(path.join(__dirname, 'src/frontend-bundle.ts'), frontendBundle, 'utf-8');

// esbuild 打包 (absroot 保证不受 cwd 影响)
const absroot = __dirname;
esbuild.buildSync({
    absWorkingDir: absroot,
    entryPoints: [path.join(absroot, 'src/index.ts')],
    bundle: true,
    outfile: path.join(absroot, 'dist/worker.js'),
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    minify: false,
    banner: {
        js: `// Worker 智能中控 — 前后端分离构建 (${new Date().toISOString()})`
    }
});

console.log('✅ Build complete → dist/worker.js');
