@echo off
REM === Unset proxy (Cloudflare direct connect) ===
set HTTP_PROXY=
set HTTPS_PROXY=
REM === DNS fix: Node.js DNS (127.0.0.1 broken) -> auto fallback ===
set NODE_OPTIONS=--require %~dp0dns-fix.js

REM Full local check chain, same order as CI (.github/workflows/ci.yml):
REM   build -> typecheck -> verify -> tests
REM build must run first: it generates src/frontend-bundle.ts which tsc needs.
REM
REM Tooling is invoked through the node_modules\.bin shims instead of `pnpm exec`:
REM  1) pnpm runs a dependency status check before any script, and when node_modules
REM     was created by a different pnpm version than package.json declares, it insists
REM     on purging and reinstalling node_modules -- which it refuses to do without a
REM     TTY (ERR_PNPM_ABORTED_REMOVE_MODULES_DIR_NO_TTY), failing the whole chain.
REM  2) The .bin shims are generated by whatever package manager installed the deps
REM     (pnpm / npm / yarn) and point at each package's declared bin entry, so this
REM     script also survives a different package manager or an upstream layout change.
REM CI still uses pnpm, where the environment is clean and reproducible.
cd /d %~dp0

if not exist node_modules\.bin\vitest.cmd (
    echo.
    echo [FAIL] node_modules is missing or incomplete. Run install.bat first.
    pause
    exit /b 1
)

echo.
echo === [1/4] Build ===
node build.js
if %errorlevel% neq 0 goto :fail

echo.
echo === [2/4] Typecheck (tsc --noEmit) ===
call node_modules\.bin\tsc.cmd --noEmit
if %errorlevel% neq 0 goto :fail

echo.
echo === [3/4] Verify (structure / routes / CSP / anti-patterns) ===
node verify.js
if %errorlevel% neq 0 goto :fail

echo.
echo === [4/4] Tests (vitest run) ===
call node_modules\.bin\vitest.cmd run
if %errorlevel% neq 0 goto :fail

echo.
echo [OK] All checks passed. Next: deploy.bat
pause
exit /b 0

:fail
echo.
echo [FAIL] Check chain failed above. Fix the errors before deploying.
pause
exit /b 1
