@echo off
REM === Unset proxy (Cloudflare direct connect) ===
set HTTP_PROXY=
set HTTPS_PROXY=
REM === DNS fix: Node.js DNS (127.0.0.1 broken) -> use gateway DNS ===
set NODE_OPTIONS=--require %~dp0dns-fix.js

REM Deploy Worker to Cloudflare
REM Prereq: run build.bat first
REM Auto-uses wrangler.local.toml if exists, otherwise wrangler.toml
REM
REM Note: on deploy, wrangler first runs the [build] command from the config
REM (now `node build.js`), so a stale dist/ is never pushed by accident.
REM That command deliberately avoids the package manager - see wrangler.toml.
REM
REM Wrangler is invoked through the node_modules\.bin shim rather than a global
REM `wrangler` / `npx wrangler`: no global install needed, no npx download, and the
REM shim is generated by whichever package manager installed the deps (pnpm/npm/yarn)
REM and points at the package's declared bin entry.
cd /d %~dp0

if not exist node_modules\.bin\wrangler.cmd (
    echo [FAIL] node_modules\.bin\wrangler.cmd not found. Run install.bat first.
    pause
    exit /b 1
)

if exist wrangler.local.toml (
    call node_modules\.bin\wrangler.cmd deploy -c wrangler.local.toml
) else (
    echo [WARN] wrangler.local.toml not found - falling back to wrangler.toml.
    echo        That file is a TEMPLATE: set "name" (and the KV binding) before deploying.
    call node_modules\.bin\wrangler.cmd deploy
)
pause
