@echo off
REM ============================================================
REM  Save a Cloudflare API token for non-interactive deploys.
REM  Writes deploy.local.bat which is gitignored.
REM  Create a token at https://dash.cloudflare.com/profile/api-tokens
REM  using the preset template: Edit Cloudflare Workers
REM
REM  The token is typed only here and stays on this machine.
REM ============================================================
setlocal
cd /d %~dp0

set "TOKEN="
set /p "TOKEN=Paste your Cloudflare API Token and press Enter: "
if not defined TOKEN (
    echo.
    echo [FAIL] No token entered - nothing changed.
    pause
    exit /b 1
)

> deploy.local.bat echo @echo off
>> deploy.local.bat echo REM Local deploy credential - generated by setup-deploy-token.bat
>> deploy.local.bat echo REM This file is gitignored. Do not commit it.
>> deploy.local.bat echo.
>> deploy.local.bat echo set CLOUDFLARE_API_TOKEN=%TOKEN%

echo.
echo [OK] Token saved to deploy.local.bat
echo      Next: deploy.bat
echo      Verify with: node_modules\.bin\wrangler.cmd whoami -c wrangler.local.toml
pause
exit /b 0
