@echo off
REM === Unset proxy (Cloudflare direct connect) ===
set HTTP_PROXY=
set HTTPS_PROXY=
REM === DNS fix: Node.js DNS (127.0.0.1 broken) -> auto fallback ===
set NODE_OPTIONS=--require %~dp0dns-fix.js

REM Setup secrets (first time only)
REM Sets ACCESS_CODE / GITHUB_TOKEN / ENCRYPTION_SECRET via wrangler secret
REM
REM Wrangler is invoked through the node_modules\.bin shim (generated by whichever
REM package manager installed the deps, and pointing at the package's declared bin
REM entry) instead of a hardcoded internal path such as wrangler-dist\cli.js.
cd /d %~dp0

if not exist node_modules\.bin\wrangler.cmd (
    echo [FAIL] node_modules\.bin\wrangler.cmd not found. Run install.bat first.
    pause
    exit /b 1
)

set WRANGLER_CONFIG=
if exist wrangler.local.toml set WRANGLER_CONFIG=-c wrangler.local.toml

echo.
echo === [1/3] Set panel password (ACCESS_CODE) ===
call node_modules\.bin\wrangler.cmd secret put ACCESS_CODE %WRANGLER_CONFIG%

echo.
echo === [2/3] Set GitHub Token (press Enter to skip) ===
call node_modules\.bin\wrangler.cmd secret put GITHUB_TOKEN %WRANGLER_CONFIG%

echo.
echo === [3/3] Set ENCRYPTION_SECRET (optional but recommended) ===
echo    Purpose: a dedicated key for encrypting stored API keys.
echo    With it set, changing ACCESS_CODE will NOT break already-encrypted data.
echo    IMPORTANT: the variable name must be exactly ENCRYPTION_SECRET (singular).
echo    WARNING: if accounts were already saved WITHOUT this secret, setting it now
echo             makes old ciphertext undecryptable - you must re-enter each API key.
echo    Press Enter to skip if you are unsure.
call node_modules\.bin\wrangler.cmd secret put ENCRYPTION_SECRET %WRANGLER_CONFIG%

echo.
echo Secrets stored in CF. Deploy will never touch them.
pause
