/**
 * 验证脚本：检查重构后文件的完整性
 * 用法: node verify.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const errors = [];
const warnings = [];

// ===== 1. 检查所有源文件存在 =====
const expectedFiles = [
    'src/index.ts',
    'src/cron.ts',
    'src/config/templates.ts',
    'src/lib/cloudflare-api.ts',
    'src/lib/github.ts',
    'src/lib/stats.ts',
    'src/middleware/auth.ts',
    'src/routes/index.ts',
    'src/routes/check.ts',
    'src/routes/deploy.ts',
    'src/routes/fix1101.ts',
    'src/routes/yxip.ts',
    'src/routes/zones.ts',
    'src/routes/crud.ts',
    'src/routes/loader.ts',
    'frontend/index.html',
    'frontend/css/style.css',
    'frontend/js/state.js',
    'frontend/js/accounts.js',
    'frontend/js/deploy.js',
    'frontend/js/vars.js',
    'frontend/js/history.js',
    'frontend/js/yxip.js',
    'frontend/js/workbench.js',
    'frontend/js/starfield.js',
    'build.js',
    'wrangler.toml',
    'package.json',
];

console.log('=== 1. File existence ===');
let allExist = true;
for (const f of expectedFiles) {
    const full = path.join(ROOT, f);
    if (!fs.existsSync(full)) {
        console.log(`  ❌ MISSING: ${f}`);
        errors.push(`Missing file: ${f}`);
        allExist = false;
    }
}
if (allExist) console.log(`  ✅ All ${expectedFiles.length} files present`);

// ===== 2. 检查 TS import 路径 =====
console.log('\n=== 2. Import path validation ===');
const tsFiles = expectedFiles.filter(f => f.endsWith('.ts'));
for (const f of tsFiles) {
    const content = fs.readFileSync(path.join(ROOT, f), 'utf-8');
    const imports = content.match(/from\s+['"](\.\.?\/[^'"]+)['"]/g);
    if (imports) {
        for (const imp of imports) {
            const modulePath = imp.match(/from\s+['"]([^'"]+)['"]/)[1];
            const dir = path.dirname(f);
            const resolved = path.resolve(ROOT, dir, modulePath);
            // Check .ts or .tsx or /index.ts
            const candidates = [resolved + '.ts', resolved + '.tsx', resolved + '/index.ts'];
            let found = false;
            for (const c of candidates) {
                if (fs.existsSync(c)) { found = true; break; }
            }
            if (!found) {
                // frontend-bundle is auto-generated by build.js — skip
                if (modulePath === './frontend-bundle' || modulePath.includes('frontend-bundle')) continue;
                console.log(`  ⚠️  ${f}: import "${modulePath}" — target not found at ${resolved}`);
                warnings.push(`Unresolved import: ${f} -> ${modulePath}`);
            }
        }
    }
}
console.log('  ✅ Import check complete');

// ===== 3. 检查前端 JS 没有残留模板字面量语法错误 =====
console.log('\n=== 3. Frontend JS syntax check ===');
const jsFiles = expectedFiles.filter(f => f.startsWith('frontend/js/'));
for (const f of jsFiles) {
    const content = fs.readFileSync(path.join(ROOT, f), 'utf-8');
    // Check for unbalanced template literals
    const backtickCount = (content.match(/`/g) || []).length;
    if (backtickCount % 2 !== 0) {
        console.log(`  ❌ ${f}: Unbalanced backticks (${backtickCount})`);
        errors.push(`Unbalanced backticks in ${f}`);
    }
    // Check for unmatched ${ without closing }
    const openDollar = (content.match(/\$\{/g) || []).length;
    const closeBrace = (content.match(/}/g) || []).length; // rough
    // Check for leftover Python/JS template issues
    const tripleBacktick = (content.match(/```/g) || []).length;
    if (tripleBacktick % 2 !== 0) {
        console.log(`  ❌ ${f}: Unbalanced triple backticks`);
        errors.push(`Unbalanced triple backticks in ${f}`);
    }
}
console.log('  ✅ Frontend JS syntax check complete');

// ===== 4. 检查 HTML 结构完整性 =====
console.log('\n=== 4. HTML structure check ===');
const html = fs.readFileSync(path.join(ROOT, 'frontend/index.html'), 'utf-8');
const openDivs = (html.match(/<div/g) || []).length;
const closeDivs = (html.match(/<\/div>/g) || []).length;
console.log(`  <div>: ${openDivs} open, ${closeDivs} close`);
if (openDivs !== closeDivs) {
    console.log(`  ⚠️  DIV mismatch (${openDivs} vs ${closeDivs}) — may include self-closing or SVG`);
    warnings.push(`DIV count mismatch: ${openDivs} open vs ${closeDivs} close`);
}

// Check critical IDs exist both in HTML and JS references
const htmlIds = new Set();
const idMatches = html.matchAll(/id="([^"]+)"/g);
for (const m of idMatches) htmlIds.add(m[1]);

// Check that key IDs exist
const criticalIds = ['account_body', 'account_form', 'vars_cmliu', 'vars_joey', 'vars_ech',
    'batch_deploy_modal', 'yxip_modal', 'history_modal', 'workbench_modal', 'starfield'];
const missingIds = criticalIds.filter(id => !htmlIds.has(id));
if (missingIds.length > 0) {
    console.log(`  ❌ Missing critical HTML IDs: ${missingIds.join(', ')}`);
    errors.push(`Missing HTML IDs: ${missingIds.join(', ')}`);
} else {
    console.log('  ✅ All critical HTML IDs present');
}

// ===== 5. 检查关键函数是否在前端 JS 中定义 =====
console.log('\n=== 5. Function coverage check ===');
const allJS = jsFiles.map(f => fs.readFileSync(path.join(ROOT, f), 'utf-8')).join('\n');
const criticalFuncs = [
    'init', 'renderTable', 'loadAccounts', 'saveAccount', 'deploy',
    'fix1101', 'doBatchDeploy', 'openBatchDeployModal',
    'loadVars', 'addVarRow', 'removeVarRow', 'refreshUUID',
    'openVersionHistory', 'refreshHistory', 'toggleFavorite',
    'showYxipModal', 'doYxipDeploy', 'fetchYxipRegions',
    'openWorkbench', 'wbLog', 'closeWorkbench',
    'toggleTheme', 'initStarfield', 'applyTheme',
    'openAccountManage', 'confirmDeleteWorker',
    'loadGlobalConfig', 'saveAutoConfig',
    'selectSyncAccount', 'doSync', 'renderProxySelector',
    'checkUpdate', 'checkDeployConfig',
    'fetchZonesForAccount', 'updateZoneInfo',
    'toggleEchToken', 'promptChangeSubdomain',
    'yxipSelectAll', 'yxipSelectNone', 'toggleYxipRegion',
    'openFavoritesPanel', 'closeFavoritesPanel',
    'toggleBatchInputs', 'editAccount', 'delAccount', 'resetFormForAdd',
];

const missingFuncs = [];
for (const fn of criticalFuncs) {
    if (!allJS.includes(`function ${fn}(`) && !allJS.includes(`function ${fn} (`) &&
        !allJS.includes(`async function ${fn}(`) && !allJS.includes(`async function ${fn} (`)) {
        // Check if it's a variable assignment like `let fn =`
        if (!allJS.match(new RegExp(`(let|const|var)\\s+${fn}\\s*=`))) {
            missingFuncs.push(fn);
        }
    }
}
if (missingFuncs.length > 0) {
    console.log(`  ❌ Missing functions: ${missingFuncs.join(', ')}`);
    errors.push(`Missing frontend functions: ${missingFuncs.join(', ')}`);
} else {
    console.log(`  ✅ All ${criticalFuncs.length} critical functions found`);
}

// ===== 6. 检查后端路由注册完整性 =====
console.log('\n=== 6. API route coverage ===');
const routesTS = fs.readFileSync(path.join(ROOT, 'src/routes/index.ts'), 'utf-8') + String.fromCharCode(10) + fs.readFileSync(path.join(ROOT, 'src/routes/crud.ts'), 'utf-8') + String.fromCharCode(10) + fs.readFileSync(path.join(ROOT, 'src/routes/loader.ts'), 'utf-8');
const originalRoutes = [
    'GET /api/accounts', 'POST /api/accounts',
    'GET /api/settings', 'POST /api/settings',
    'GET /api/deploy_config',
    'GET /api/favorites', 'POST /api/favorites',
    'GET /api/auto_config', 'POST /api/auto_config',
    'GET /api/check_update', 'GET /api/get_code',
    'POST /api/deploy', 'POST /api/batch_deploy',
    'POST /api/zones', 'POST /api/all_workers',
    'POST /api/delete_worker', 'POST /api/fetch_bindings',
    'POST /api/get_subdomain', 'POST /api/change_subdomain',
    'GET /api/stats', 'POST /api/fix_1101',
    'GET /api/get_regions_data', 'POST /api/save_yxip',
];

// Routes are registered either directly as m.set('GET /api/x', ...) or via lazyRoutes array
// Check both patterns
const missingRoutes = originalRoutes.filter(r => {
    const [method, routePath] = r.split(' ');
    // Check for direct m.set pattern
    if (routesTS.includes(`'${r}'`) || routesTS.includes(`"${r}"`)) return false;
    // Check for lazyRoutes array pattern: ['METHOD', '/path', ...]
    if (routesTS.includes(`'${method}', '${routePath}'`)) return false;
    return true;
});
if (missingRoutes.length > 0) {
    console.log(`  ❌ Missing routes: ${missingRoutes.join(', ')}`);
    errors.push(`Missing API routes: ${missingRoutes.join(', ')}`);
} else {
    console.log(`  ✅ All ${originalRoutes.length} API routes registered`);
}

// 特殊检查: POST /api/login 在 src/index.ts 内联处理（不在路由表中）
const loginInline = fs.readFileSync(path.join(ROOT, 'src/index.ts'), 'utf-8');
if (!loginInline.includes("url.pathname === '/api/login'") || !loginInline.includes("request.method === 'POST'")) {
    console.log('  ❌ POST /api/login inline handler missing in src/index.ts');
    errors.push('POST /api/login inline handler missing');
} else {
    console.log('  ✅ POST /api/login handled inline in src/index.ts');
}

// ===== 7. 检查 echo 后端模块导出了被 index.ts 使用的函数 =====
console.log('\n=== 7. Export/import consistency ===');
const indexTS = fs.readFileSync(path.join(ROOT, 'src/index.ts'), 'utf-8');
const entryImports = [
    { file: 'middleware/auth', exports: ['requireAccessCode', 'requireCookie', 'checkCsrf', 'generateAuthToken'] },
    { file: 'lib/cloudflare-api', exports: ['jsonError'] },
    { file: 'routes/index', exports: ['getRoute'] },
    { file: 'cron', exports: ['handleCronJob'] },
    { file: 'config/templates', exports: ['TEMPLATES', 'ECH_PROXIES', 'KV_KEYS', 'MANIFEST'] },
    // frontend-bundle is auto-generated by build.js — skip verification
    // { file: 'frontend-bundle', exports: ['FRONTEND_HTML', 'FRONTEND_CSS', 'FRONTEND_JS'] },
];

for (const { file, exports: exp } of entryImports) {
    const filePath = path.join(ROOT, 'src', file + '.ts');
    if (!fs.existsSync(filePath)) {
        console.log(`  ❌ ${file}.ts not found`);
        errors.push(`Missing: src/${file}.ts`);
        continue;
    }
    const content = fs.readFileSync(filePath, 'utf-8');
    for (const e of exp) {
        if (!content.includes(`export`) || !content.includes(e)) {
            // More precise check
            if (!new RegExp(`export\\s+(const|function|async function|let|var|class|interface|type)\\s+${e}\\b`).test(content) &&
                !new RegExp(`export\\s*\\{\\s*[^}]*\\b${e}\\b[^}]*\\}`).test(content)) {
                console.log(`  ⚠️  ${file}.ts: export "${e}" not found with expected pattern`);
                warnings.push(`Export check: ${file}.ts may not export "${e}"`);
            }
        }
    }
}
console.log('  ✅ Export check complete');

// ===== SUMMARY =====
console.log('\n' + '='.repeat(60));
console.log('VERIFICATION SUMMARY');
console.log('='.repeat(60));
console.log(`  Errors:   ${errors.length}`);
console.log(`  Warnings: ${warnings.length}`);

if (errors.length > 0) {
    console.log('\n❌ ERRORS:');
    errors.forEach(e => console.log(`  - ${e}`));
}
if (warnings.length > 0) {
    console.log('\n⚠️  WARNINGS:');
    warnings.forEach(w => console.log(`  - ${w}`));
}

if (errors.length === 0) {
    console.log('\n✅ All critical checks passed!');
    console.log('Run `npm install && npm run build` to produce dist/worker.js');
}

process.exit(errors.length > 0 ? 1 : 0);
